// Generated by tools/embed_web.py - do not edit by hand.

#pragma once

#include <stddef.h>
#include <stdint.h>

// The dashboard, pre-gzipped. Served straight out of flash with a
// Content-Encoding: gzip header - the board never compresses at runtime.
//
// Declared extern rather than defined inline because the ESP32 Arduino core
// builds as gnu++11, which has no inline variables.
extern const uint8_t WEB_UI_GZ[];
extern const size_t WEB_UI_GZ_LEN;
