#!/usr/bin/env python3
"""Turn the built dashboard into C source the firmware can serve.

The board has no filesystem step: the UI is compiled into the binary, so one
`pio run -t upload` ships both. The generated files are committed, which means
cloning and flashing needs no Node toolchain at all - only rebuilding the UI
does.

Run after changing anything under web/src:

    cd web && npm run build
    python tools/embed_web.py
"""

import gzip
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "web" / "dist" / "index.html"
OUT_DIR = ROOT / "src" / "components" / "wifi" / "web_server"
HEADER = OUT_DIR / "web_ui.h"
IMPL = OUT_DIR / "web_ui.cpp"

BANNER = "// Generated by tools/embed_web.py - do not edit by hand.\n"

HEADER_BODY = """#pragma once

#include <stddef.h>
#include <stdint.h>

// The dashboard, pre-gzipped. Served straight out of flash with a
// Content-Encoding: gzip header - the board never compresses at runtime.
//
// Declared extern rather than defined inline because the ESP32 Arduino core
// builds as gnu++11, which has no inline variables.
extern const uint8_t WEB_UI_GZ[];
extern const size_t WEB_UI_GZ_LEN;
"""


def main() -> int:
    if not SOURCE.exists():
        print("missing %s - run `npm run build` in web/ first" % SOURCE)
        return 1

    raw = SOURCE.read_bytes()
    # mtime=0 so rebuilding identical content produces an identical file and
    # does not show up as a spurious diff.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(packed), 16):
        chunk = packed[i : i + 16]
        lines.append("    " + " ".join("0x%02x," % b for b in chunk))

    impl = [
        BANNER,
        '// Source: web/dist/index.html (%d bytes, %d gzipped)\n\n'
        % (len(raw), len(packed)),
        '#include "web_ui.h"\n\n',
        "const uint8_t WEB_UI_GZ[] = {\n",
        "\n".join(lines),
        "\n};\n\n",
        "const size_t WEB_UI_GZ_LEN = sizeof(WEB_UI_GZ);\n",
    ]

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(BANNER + "\n" + HEADER_BODY, encoding="utf-8")
    IMPL.write_text("".join(impl), encoding="utf-8")

    ratio = 100 * len(packed) / len(raw)
    print("raw      %7d bytes" % len(raw))
    print("gzipped  %7d bytes  (%.1f%%)" % (len(packed), ratio))
    print("wrote    %s" % IMPL.relative_to(ROOT))
    print("         %s" % HEADER.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
